### ISSUE TITLE
Does not take into account the start header level

### ISSUE THREAD

**Issue by MelodyDuplaix** [HoBeedzc/obsidian-header-enhancer-plugin#1]
I don't know if it's a bug or if I don't understand a parameter.
I almost never use the level 1 header, so I'd like my level 2 headers to be numbered 1 , 2 etc... and not 0.1, 0.2, etc.... However, no matter how many times I change this setting (start header level), the numbering is always wrong in my notes, despite having restarted obsidian in the meantime. I have the impression that this parameter is not taken into account. Is it possible to correct it?
Thank you in advance

**Comment by HoBeedzc** [comment]
Hi there,

Thank you for bringing this issue to our attention. I appreciate your patience and your detailed description of the problem.

After my investigation, I can confirm that this bug does indeed exist. The good news is that the bug has already been addressed in PR#2 , and it has been included in the latest release of the plugin, version 0.0.4. To resolve the issue, all you need to do is update the plugin to the most recent version.

I want to express my gratitude for bringing this issue to our attention. If you encounter any further problems during your use of the plugin, please don't hesitate to reach out to me at any time. Your feedback is greatly appreciated.

Thank you once again.

Best regards,
Hobee Liu
