### ISSUE TITLE
阅读视图下标题内容不对齐

### ISSUE THREAD

**Issue by olrk** [HoBeedzc/obsidian-header-enhancer-plugin#10]
你好，我发现标题内容在阅读视图下会对不齐，在实时阅览模式下是对齐的。
下图为阅读视图下的截图，可以看到 a 与 b 是不对齐的：
![image](https://github.com/HoBeedzc/obsidian-header-enhancer-plugin/assets/53005753/4af220a5-a821-4c44-a795-2509ff8cc6aa)

**Comment by HoBeedzc** [comment]
olrk 你好，
这个现象是由于编号和标题之间使用 Tab 进行分隔导致的，这并不是bug。
但目前插件不支持修改默认分隔符，下个版本将会支持这个功能，你可以关注 feat/support-space-splitor 这个分支的更新
我也会在插件更新的第一时间回复此 issue
