### ISSUE TITLE
Header Numbering to be ignored in code sections

### ISSUE THREAD

**Issue by HoffiMuc** [HoBeedzc/obsidian-header-enhancer-plugin#16]
if I have comments in code-blocks where the language uses '#' as comment, the plugin adds and increases the header count

if I have, e.g.

```
# 2 Header

<threeTicks>bash
cd public
# use serve --port 3000 to serve from port 3000
npx quartz build
npx serve public/
<threeTicks>

# 3 next Header
```

The plugin treats the comment line inside code sections as a markdown header, thus giving me:

```
# 2 Header

<threeTicks>bash
cd public
# 3 use serve --port 3000 to serve from port 3000
npx quartz build
npx serve public/
<threeTicks>

# 4 next Header
```

would it be possible to ignore anything in between threeTicks (```)
?

**Comment by HoBeedzc** [comment]
Thank you for reporting this issue! I've successfully identified the issue, and rest assured, it will be addressed in the upcoming release/version.
