### ISSUE TITLE
建议修改为不自动编号，根据YAML区的字段来决定开启

### ISSUE THREAD

**Issue by kickTiger** [HoBeedzc/obsidian-header-enhancer-plugin#4]
并不是所有的标题都需要进行编号，也避免强行修改一些页面。

### 1、关于自动编号和参数
- 不要自动开始编号，改由YAML区来决定是否开启。
- 建议 YAML的参数决定编号的参数，

参数比如：
```
number headings: auto, first-level 2, max 1, start-at 1, 1.1
```
这样的话，就会自动编号，然后第一层，和最大层，都按照参数来。

### 2、关于增加命令快速添加YAML属性。
建议在命令面板增加一个，添加 上面默认参数的选项，方便能够插入。
默认YAML，根据在设置界面里设置的参数来决定，避免复杂输入。

### **小结**：
这个是 **Number Headings** 插件的类似功能，这个插件的逻辑非常好，
但是最近属性升级之后，无法在YAML去插入参数，也无法识别已经添加的YAML参数了。
希望作者可以借鉴，开发出替代品。

万分感谢！

**Comment by HoBeedzc** [comment]
感谢您对插件的关注，目前 0.0.6 版本可以根据 yaml 进行编号，如果在使用中有任何问题欢迎提出。
